version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: pauloreis/nginx:prod
    container_name: nginx
    restart: unless-stopped
    networks:
      - node-network
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pauloreis/node:prod
    container_name: app
    restart: always
    command: node server.js
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    tty: true
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
